# Array Calculator

*Purpose: To demonstrate proficiency an dunderstanding of Data Types in Python, Basics of NumPy Arrays, and Universal Functions*

In [3]:
import numpy as np

#Option to create array by entering elements
def create_array_manually():
    user_input = input("Enter the elements of the array, seperated by spaces: ")
    elements = list(map(float, user_input.split()))
    return np.array(elements)

#Option to generate a random array
def create_random_array():
    #expected_values = {'1d', '2d', '3d'}

    #Define array dimensions
    user_input = input("What dimension array to generate (1D/2D/3D)?").strip().lower()
    if user_input == '1d':
        size = int(input("Enter the size of the array:"))
    elif user_input == '2d':
        size_x = int(input("Enter the row size of the array:")) 
        size_y = int(input("Enter the column size of the array:"))  
        size = (size_x, size_y)
    elif user_input == '3d':
        size_x = int(input("Enter the row size of the array:")) 
        size_y = int(input("Enter the column size of the array:"))  
        size_z = int(input("Enter the depth size of the array:"))
        size = (size_x, size_y, size_z)
    else:
        print("Invalid option. Using default 1D array size.")
        size = 5

    #Define array type      
    array_type = input("Enter the type of random array (int/float): ").strip().lower() #strip() for error handling
    if array_type == "int":
        low = int(input("Enter the lower bound:"))
        high  = int(input("Enter the higher bound:"))
        return np.random.randint(low, high + 1, size)
    elif array_type == "float":
        low = float(input("Enter the lower bound:"))
        high =  float(input("Enter the upper bound:"))
        return np.random.uniform(low, high, size)
    else:
        print("Invalid type, defaulting to float array with range 0 to 1.")
        return np.random.rand(size)

#Array menu creation
def create_array():
    print("\nChoose how to create the array:")
    print("1. Manually enter elements")
    print("2. Generate a random array")
    choice = int(input("Enter your choice (1 or 2): "))

    if choice == 1:
        return create_array_manually()
    elif choice == 2:
        return create_random_array()
    else:
        print("Invalid choice. Defaulting to manual input.")
        return create_array_manually()
    

#Menu
def display_menu():
    print("\nChoose an operation to perform:")
    print("1. Print array")
    print("2. Square each element")
    print("3. Take the square root of each element")
    print("4. Compute the exponential of each element")
    print("5. Compute the sine of each element")
    print("6. Compute the mean of the array")
    print("7. Compute the standard deviation of the array")
    print("8. Find the maximum value in the array")
    print("9. Find the minimum value in the array")
    print("10. Exit")

#Array operations
def perform_operation(arr, choice):
    if choice == 1: #print array
        return arr
    elif choice == 2: #square array
        return np.square(arr)
    elif choice == 3: #square root of array
        return np.sqrt(arr)
    elif choice == 4: #exponential of array
        return np.exp(arr)
    elif choice == 5: #sine of array
        return np.sin(arr)
    elif choice == 6: #mean of array
        return np.mean(arr)
    elif choice == 7: #standard deviation
        return np.std(arr)
    elif choice == 8: #maximum
        return np.max(arr)
    elif choice == 9: #minimum
        return np.min(arr)
    elif choice == 10:
        return None
    else:
        print("Invalid choice. Please enter a number.")


# Main Program:

print("Welcome to the NumPy Array Operations Program!")
arr = create_array()
print("Your Array:\n", arr)

while True:
    display_menu()
    choice = int(input("Enter your choice from the menu (1-10)"))

    if choice == 10:
        print("Exiting program. Goodbye!")
        break

    result = perform_operation(arr, choice)

    if result is not None:
        print(f"\nResult: {result}")


Welcome to the NumPy Array Operations Program!

Choose how to create the array:
1. Manually enter elements
2. Generate a random array
Your Array:
 [[ 86.40523208  77.87788776  83.24490582 155.99930382 178.80324863]
 [187.95815642 125.85333454 120.72349199  76.66613799 164.01199255]
 [131.59208341 172.96389795 197.68613541 104.33141767 102.89230137]
 [100.24461986  70.46314062 121.61939974 138.73230349 175.17677787]]

Choose an operation to perform:
1. Print array
2. Square each element
3. Take the square root of each element
4. Compute the exponential of each element
5. Compute the sine of each element
6. Compute the mean of the array
7. Compute the standard deviation of the array
8. Find the maximum value in the array
9. Find the minimum value in the array
10. Exit
Exiting program. Goodbye!
