       38. Consider a generator function that generates 10 integers and use it to build an array

       44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
       
       51. Create a structured array representing a position (x,y) and a color (r,g,b)

# Optimal 2D Array Shape Creation

In [21]:
#Import modules
import numpy as np
import math

#Generator function that genearates N integers
def gen_integers(N):
    for i in range(N):
        yield i

#Function to get best 2D shape array
def find_optimal_shape(n):
    sqrt_n = int(math.sqrt(n))
    for i in range(sqrt_n, 0, -1):
        if n % i == 0:
            return (i, n // i)
    return (n, 1)

#Building a numpy array with the generator function
n=13
my_list = list(gen_integers(n))
print(f"{my_list}\n")

#Building NumPy array
my_arr = np.array(my_list).reshape((find_optimal_shape(n)))
print(my_arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]]


# Cartesian Coordinates to Polar Coordinates

In [8]:
import numpy as np
cartesian_coords = np.random.rand(10, 2) * 20 - 10
print(f"{cartesian_coords}\n")
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]

r = np.sqrt(x ** 2 + y ** 2)
theta = np.arctan(y, x)

polar_coords = np.column_stack((r,theta))
print(f"{polar_coords}\n")

[[-9.95622736  4.12959266]
 [ 2.68655542 -0.36386188]
 [-8.55065463  4.07648385]
 [ 6.55158466  9.9966026 ]
 [-3.77739155  7.70924595]
 [-6.94547798 -7.04528572]
 [ 3.07722864  0.53584752]
 [ 9.80450486 -9.16041811]
 [-6.96433078  6.84044398]
 [ 0.55647839  4.52000197]]

[[10.77868261  1.33321506]
 [ 2.71108382 -0.34897017]
 [ 9.47266674  1.33023715]
 [11.95221006  1.47109403]
 [ 8.58493797  1.44180221]
 [ 9.89321562 -1.42979928]
 [ 3.12353464  0.4919127 ]
 [13.41795721 -1.46206157]
 [ 9.76184292  1.42563525]
 [ 4.55412845  1.35306468]]



# Strucutred Arrays

In [15]:
import numpy as np

data = np.zeros(5, dtype=[('position', [ ('x', float, 1), 
                                        ('y', float, 1)]),
                            ('color', [ ('r', float, 1),
                                       ('g', float, 1),
                                       ('b', float, 1)])])

data['position'] = [(1.0, 2.0), (3.0, 4.0), (5.0, 6.0), (7.0, 8.0), (9.0, 10.0)]
data['color'] = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (255, 0, 255)]

print(data)

[((1.,  2.), (255.,   0.,   0.)) ((3.,  4.), (  0., 255.,   0.))
 ((5.,  6.), (  0.,   0., 255.)) ((7.,  8.), (255., 255.,   0.))
 ((9., 10.), (255.,   0., 255.))]


/var/folders/s0/399qjfv1781c67074w7lg0tc0000gn/T/ipykernel_19197/3009307543.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  data = np.zeros(5, dtype=[('position', [ ('x', float, 1),


In [14]:
import numpy as np

def extract_subpart(arr, center, shape, fill_value = 0):
    center = np.array(center)
    shape = np.array(shape)
    half_shape = shape // 2

    start = center - half_shape
    end = start + shape

    pad_width = np.maximum(half_shape, 0)
    padded_arr = np.pad(arr, [(pad_width[i], pad_width[i]) for i in range(arr.ndim)], constant_values = fill_value)

    slices = tuple(slice(start[i], end[i]) for i in range(arr.ndim))
    subpart = padded_arr[slices]

    return subpart

arr = np.arange(16).reshape(4,4)
center = (1, 1)
shape = (3, 3)
fill_value = -1

subpart = extract_subpart(arr, center, shape, fill_value)
print(f"Original array: \n{arr}\n")
print(f"Extracted subpart centered at {center} with shape {shape}: \n{subpart}\n")

Original array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted subpart centered at (1, 1) with shape (3, 3): 
[[-1 -1 -1]
 [-1  0  1]
 [-1  4  5]]

