       38. Consider a generator function that generates 10 integers and use it to build an array

       44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
       
       51. Create a structured array representing a position (x,y) and a color (r,g,b)

       https://github.com/rougier/numpy-100

## Optimal 2D Array Shape Creation

In [36]:
#Import modules
import numpy as np
import math

#Generator function that genearates N integers
def gen_integers(N):
    for i in range(N):
        yield i

#Function to get best 2D shape array
def find_optimal_shape(n):
    sqrt_n = int(math.sqrt(n))
    for i in range(sqrt_n, 0, -1):
        if n % i == 0:
            return (i, n // i)
    return (n, 1)

#Building a numpy array with the generator function
n=15
my_list = list(gen_integers(n))
print(f"{my_list}\n")

#Building NumPy array
my_arr = np.array(my_list).reshape((find_optimal_shape(n)))
print(my_arr)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### Cartesian Coordinates to Polar Coordinates

In [25]:
import numpy as np
cartesian_coords = np.random.rand(8, 2) * 20 - 10
print("Cartesian Coordinates (x, y):")
print(f"{cartesian_coords}\n")
x, y = cartesian_coords[:, 0], cartesian_coords[:, 1]

r = np.sqrt(x ** 2 + y ** 2)
theta = np.arctan(y, x)
print("Polar Coordinates (R, theta):")
polar_coords = np.column_stack((r,theta))
print(f"{polar_coords}\n")

Cartesian Coordinates (x, y):
[[-8.26059879 -8.93480275]
 [-9.02256515  9.7287643 ]
 [-2.53292918  5.92863116]
 [ 0.96602809  7.66974896]
 [-2.50571455  4.66322113]
 [-1.05398285  7.34690694]
 [-1.87137071  5.1722269 ]
 [ 7.24463359 -0.71161042]]

Polar Coordinates (R, theta):
[[12.16832744 -1.45933829]
 [13.26859211  1.46836807]
 [ 6.44704565  1.40369618]
 [ 7.73034665  1.44114533]
 [ 5.29379228  1.35955162]
 [ 7.42212378  1.43551596]
 [ 5.50035994  1.37981243]
 [ 7.27949897 -0.61847576]]



# Strucutred Arrays

In [32]:
import numpy as np

data = np.zeros(5, dtype=[('position', [ ('x', 'float64'), 
                                        ('y', 'float64')]),
                            ('color', [ ('r', 'float64'),
                                       ('g', 'float64'),
                                       ('b', 'float64')])])

data['position'] = [(1.0, 2.0), (3.0, 4.0), (5.0, 6.0), (7.0, 8.0), (9.0, 10.0)]
data['color'] = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (255, 0, 255)]

print(data)

[((1.,  2.), (255.,   0.,   0.)) ((3.,  4.), (  0., 255.,   0.))
 ((5.,  6.), (  0.,   0., 255.)) ((7.,  8.), (255., 255.,   0.))
 ((9., 10.), (255.,   0., 255.))]


In [14]:
import numpy as np

def extract_subpart(arr, center, shape, fill_value = 0):
    center = np.array(center)
    shape = np.array(shape)
    half_shape = shape // 2

    start = center - half_shape
    end = start + shape

    pad_width = np.maximum(half_shape, 0)
    padded_arr = np.pad(arr, [(pad_width[i], pad_width[i]) for i in range(arr.ndim)], constant_values = fill_value)

    slices = tuple(slice(start[i], end[i]) for i in range(arr.ndim))
    subpart = padded_arr[slices]

    return subpart

arr = np.arange(16).reshape(4,4)
center = (1, 1)
shape = (3, 3)
fill_value = -1

subpart = extract_subpart(arr, center, shape, fill_value)
print(f"Original array: \n{arr}\n")
print(f"Extracted subpart centered at {center} with shape {shape}: \n{subpart}\n")

Original array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted subpart centered at (1, 1) with shape (3, 3): 
[[-1 -1 -1]
 [-1  0  1]
 [-1  4  5]]

